#include <ntddk.h>

#define IOCTL_READWRITE           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_GET_BASE_ADDRESS  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IOCTL_GET_GUARDED_REGION     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define CODE_SECURITY        0x12A3B45
#define PAGE_OFFSET_SIZE 12

static const UINT64 PMASK = (~0xfull << 8) & 0xfffffffffull;